apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argocd # the namespace must me "argocd"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: repo url # https://github.com/argoproj/argocd-example-apps
  username: argo-demo #name of access token
  password: github access token of repo # hexa string token
  project: default # name of project
